export function openMermaidDiagram(mermaidCode: string): void {
    const html = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Process Diagram - Ava</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 20px;
            background: #f5f5f5;
            display: flex;
            flex-direction: column;
            align-items: center;
            min-height: 100vh;
        }
        .header {
            background: white;
            padding: 15px;
            border-radius: 8px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
            margin-bottom: 15px;
            text-align: center;
            width: 100%;
            max-width: 1000px;
            display: flex;
            align-items: center;
            justify-content: center;
            gap: 10px;
        }
        .header h1 {
            margin: 0;
            color: #333;
            font-size: 18px;
        }
        .logo {
            width: 24px;
            height: 24px;
        }
        .diagram-container {
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
            width: 98%;
            max-width: 1200px;
            overflow: auto;
        }
        #diagram {
            display: flex;
            justify-content: center;
            align-items: center;
        }
        .error {
            color: #d32f2f;
            text-align: center;
            padding: 20px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>🎨 Process Diagram</h1>
        <p>Generated by Ava - Advanced Vocus Assistant</p>
    </div>
    
    <div class="diagram-container">
        <div id="diagram">Loading diagram...</div>
    </div>

    <script type="module">
        import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';
        
        mermaid.initialize({
            startOnLoad: false,
            theme: 'default',
            flowchart: {
                htmlLabels: true,
                curve: 'basis'
            }
        });

        const mermaidCode = \`${mermaidCode.replace(/`/g, '\\`')}\`;
        
        try {
            const { svg } = await mermaid.render('diagram-' + Date.now(), mermaidCode);
            document.getElementById('diagram').innerHTML = svg;
        } catch (error) {
            console.error('Mermaid render error:', error);
            document.getElementById('diagram').innerHTML = \`
                <div class="error">
                    <h3>Unable to render diagram</h3>
                    <p>There was an error processing the diagram code.</p>
                    <details>
                        <summary>Show code</summary>
                        <pre style="text-align: left; background: #f5f5f5; padding: 10px; border-radius: 4px; margin-top: 10px;">\${mermaidCode}</pre>
                    </details>
                </div>
            \`;
        }
    </script>
</body>
</html>`;

    const newWindow = window.open('', '_blank');
    if (newWindow) {
        newWindow.document.write(html);
        newWindow.document.close();
    } else {
        console.error('Failed to open new window for Mermaid diagram');
    }
}